baseURL = "https://evanap.com/"
languageCode = "en-us"
title = "Evan's Notes"
theme = "hugo-theme-diary"

googleAnalytics = "UA-161429564-1"

pygmentsCodefences = true
pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[params]
subtitle = "Notes I've taken"
enableReadingTime=true
  project_name = "Evan's Notes"
  project_tagline = "A personal page to pour my thougts and stuffs I learn."

  dateFormat = "2006-01-02"
  footer = "© 2020 evanap. Made with [Hugo](https://gohugo.io/). Themed by [Cayman](https://github.com/zwbetz-gh/cayman-hugo-theme)."

  code_background_color = "#f3f6fa"
  code_text_color = "#567482"

[menu]
  [[menu.nav]]
    name = "Notes"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.nav]]
    name = "GitHub"
    url = "https://github.com/evanap"
    weight = 4

[[menu.main]]
url = "/about"
name = "About"
weight = 3
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2
[[menu.main]]
url = "/posts"
name = "Posts"
weight = 1
[[menu.main]]
url = "https://github.com/evanap"
name = "GitHub"
weight = 4
